#/bin/sh

CONFIG_FILE=../autogen/sl_component_catalog.h
DISABLE_LIST="SL_CATALOG_CLI_PRESENT SL_CATALOG_LEGACY_PRINTF_PRESENT SL_CATALOG_ZIGBEE_ZCL_CLI_PRESENT SL_CATALOG_ZIGBEE_STACK_DIAGNOSTICS_PRESENT SL_CATALOG_ZIGBEE_DEBUG_PRINT_PRESENT 
 SL_CATALOG_ZIGBEE_CORE_CLI_PRESENT SL_CATALOG_ZIGBEE_CLI_PRESENT SL_CATALOG_PRINTF_PRESENT SL_CATALOG_LEGACY_PRINTF_PRESENT" 

if [ "$1" = "release" ] ; then
	for component in ${DISABLE_LIST}
	do
		echo ${component}
		sed -i "/$component/ s/^#/\/\/#/" ${CONFIG_FILE}
	done
else
    sed -i "s:\/\/#:#:g" ${CONFIG_FILE}
fi
 